<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="VNUML" nsURI="http:///VNUML.ecore" nsPrefix="VNUML">
    <eClassifiers xsi:type="ecore:EClass" name="Vnuml">
      <eStructuralFeatures xsi:type="ecore:EReference" name="global" lowerBound="1"
          eType="#/1/Global" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="net" upperBound="-1"
          eType="#/1/Net" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vm" upperBound="-1" eType="#/1/Vm"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Global">
      <eStructuralFeatures xsi:type="ecore:EReference" name="version" lowerBound="1"
          eType="#/1/Version" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="automac" eType="#/1/Automac"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="simulationName" lowerBound="1"
          eType="#/1/SimulationName" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vmMgmt" eType="#/1/VmMgmt"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vmDefaults" eType="#/1/VmDefaults"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Version">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Automac"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimulationName">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VmMgmt">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VmDefaults">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="execMode" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filesystem" eType="#/1/Filesystem"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kernel" eType="#/1/Kernel"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="console" upperBound="-1"
          eType="#/1/Console" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Net">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Vm">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filesystem" eType="#/1/Filesystem"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kernel" eType="#/1/Kernel"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="console" upperBound="-1"
          eType="#/1/Console" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="forwarding" eType="#/1/Forwarding"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="route" upperBound="-1"
          eType="#/1/Route" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="intf" upperBound="-1"
          eType="#/1/Intf" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Filesystem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Kernel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Console">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Forwarding">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Intf">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="net" lowerBound="1" eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ipv4" upperBound="-1"
          eType="#/1/Ipv4" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ipv6" upperBound="-1"
          eType="#/1/Ipv6" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ipv4">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ipv6">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Route">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gw" lowerBound="1" eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
