<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="VNUMLOspf" nsURI="http:///VNUMLOspf.ecore" nsPrefix="VNUMLOspf">
    <eClassifiers xsi:type="ecore:EClass" name="OspfConf">
      <eStructuralFeatures xsi:type="ecore:EReference" name="vm" lowerBound="1" upperBound="-1"
          eType="#/1/Vm" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Vm">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="zebraBin" eType="#/1/ZebraBin"
          defaultValueLiteral="" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ospfdBin" eType="#/1/OspfdBin"
          defaultValueLiteral="" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
          upperBound="-1" eType="#/1/Network" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="zebra" lowerBound="1"
          eType="#/1/Zebra" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ZebraBin">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OspfdBin">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Network">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ip" lowerBound="1" eType="#/1/Ip"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1"
          eType="#/1/Area" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Zebra">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ip">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Area">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="_text" lowerBound="1"
          eType="#/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
