// VNUML and ADRENALINE testbed context default MOF specification, v0.2008_10_15
//
// This file can be mofified/distributed under the terms of 
// Creative Commons Attribution-Share Alike 2.5 Spain License.
// See details at: http://creativecommons.org/licenses/by-sa/2.5/es/deed.en
// 
// Copyright (C) 2008 Fermin Galan Marquez

// This file describes two set of testbed context (one for VNUML-based
// testbeds and other for ADRENALINE) used as defaults. They are used when 
// initializeFromCIMOM=true

instance of CTM_VNUMLTestbedParameters {

	// key properties
    InstanceID = "vnuml-defaults";
    
	specVersion = "1.9";
	defaultExecMode = "mconsole";
	defaultFilesystemType = "cow";
	defaultFilesystem = "/usr/share/vnuml/filesystems/root_fs_tutorial";
	defaultKernel = "/usr/share/vnuml/kernels/linux";
	defaultConsole = "xterm";

};

instance of CTM_AdrenalineTestbedParameters {

	// key properties
    InstanceID = "adrenaline-defaults";

	zebraBin = "/users/home/grups/zebra/test_bin/zebra";
	ospfdBin = "/users/home/grups/zebra/zebra-0.94/ospfd/ospfd";
	lrmBin   = "/mnt/server/grups/zebra/lrm/lrm/lrm";
	rsvpdBin = "/mnt/server/grups/rsvpte-svn/rsvpd/rsvpd";
	rtapBin  = "/mnt/server/grups/rsvpte-svn/apitools/rtap";
	snmpdBin = "/users/home/grups/nms/Agent/snmpd_project/snmpd_project";
	olrmBin  = "/mnt/server/grups/cci/before_protection_modifications/src/olrm";
	cpbwmBin = "/mnt/server/grups/cpbwmon/src/release/cpbwm";
		
	baseMgtAddress = "10.1.1.111";
	baseConnectAddress = "10.10.0.0";
		
	baseVlan = 600;
	vlanDev = "eth0";

};

