<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:TIM="http:///TIM.ecore">
  <!-- the testbed itself (1) -->
  <TIM:TIM_TestbedScenario Name="nsfnet" xmi:id="nsfnet"/>
  
  <!-- the nodes (14) -->
  <TIM:CIM_ComputerSystem Name="WA" xmi:id="WA"/>
  <TIM:CIM_ComputerSystem Name="CA1" xmi:id="CA1"/>
  <TIM:CIM_ComputerSystem Name="CA2" xmi:id="CA2"/>
  <TIM:CIM_ComputerSystem Name="UT" xmi:id="UT"/>
  <TIM:CIM_ComputerSystem Name="CO" xmi:id="CO"/>
  <TIM:CIM_ComputerSystem Name="NE" xmi:id="NE"/>
  <TIM:CIM_ComputerSystem Name="IL" xmi:id="IL"/>
  <TIM:CIM_ComputerSystem Name="MI" xmi:id="MI"/>
  <TIM:CIM_ComputerSystem Name="PA" xmi:id="PA"/>
  <TIM:CIM_ComputerSystem Name="NY" xmi:id="NY"/>
  <TIM:CIM_ComputerSystem Name="NJ" xmi:id="NJ"/>
  <TIM:CIM_ComputerSystem Name="DC" xmi:id="DC"/>
  <TIM:CIM_ComputerSystem Name="GA" xmi:id="GA"/>
  <TIM:CIM_ComputerSystem Name="TX" xmi:id="TX"/>                          
    
  <!-- node loopback interfaces (14) -->
  <TIM:CIM_IPProtocolEndpoint xmi:id="wa-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca1-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca2-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ut-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="co-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ne-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="il-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="mi-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="pa-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ny-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="nj-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="dc-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ga-lo"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="tx-lo"/>

  <!-- node PPP interfaces (42) -->
  <TIM:CIM_IPProtocolEndpoint xmi:id="wa-ca1-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="wa-ca2-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="wa-il-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca1-ca2-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca1-ut-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca1-wa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca2-ca1-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca2-wa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ca2-tx-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ut-ca1-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ut-mi-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ut-co-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="co-ut-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="co-ne-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="co-tx-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ne-co-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ne-il-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="il-ne-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="il-wa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="il-pa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="mi-ut-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="mi-nj-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="mi-ny-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="pa-il-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="pa-ga-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="pa-ny-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="pa-nj-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ny-mi-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ny-pa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ny-dc-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="nj-mi-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="nj-pa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="nj-dc-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="dc-tx-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="dc-ny-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="dc-nj-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ga-pa-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="ga-tx-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="tx-ca2-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="tx-co-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="tx-dc-if"/>
  <TIM:CIM_IPProtocolEndpoint xmi:id="tx-ga-if"/>
  
  <!-- the IPv4 addresses for the loopback interfaces (14) -->
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.1" SubnetMask="255.255.255.0" xmi:id="wa-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.2" SubnetMask="255.255.255.0" xmi:id="ca1-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.3" SubnetMask="255.255.255.0" xmi:id="ca2-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.4" SubnetMask="255.255.255.0" xmi:id="ut-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.5" SubnetMask="255.255.255.0" xmi:id="co-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.6" SubnetMask="255.255.255.0" xmi:id="ne-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.7" SubnetMask="255.255.255.0" xmi:id="il-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.8" SubnetMask="255.255.255.0" xmi:id="mi-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.9" SubnetMask="255.255.255.0" xmi:id="pa-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.10" SubnetMask="255.255.255.0" xmi:id="ny-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.11" SubnetMask="255.255.255.0" xmi:id="nj-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.12" SubnetMask="255.255.255.0" xmi:id="dc-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.13" SubnetMask="255.255.255.0" xmi:id="ga-lo-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.50.14" SubnetMask="255.255.255.0" xmi:id="tx-lo-ip"/>

  <!-- the IPv4 addresses for the PPP interfaces (42) (/30 = 255.255.255.252) -->
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.21" SubnetMask="255.255.255.0" xmi:id="wa-ca1-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.23" SubnetMask="255.255.255.0" xmi:id="wa-ca2-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.28" SubnetMask="255.255.255.0" xmi:id="wa-il-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.13" SubnetMask="255.255.255.0" xmi:id="ca1-ca2-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.14" SubnetMask="255.255.255.0" xmi:id="ca1-ut-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.12" SubnetMask="255.255.255.0" xmi:id="ca1-wa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.31" SubnetMask="255.255.255.0" xmi:id="ca2-ca1-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.32" SubnetMask="255.255.255.0" xmi:id="ca2-wa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.37" SubnetMask="255.255.255.0" xmi:id="ca2-tx-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.41" SubnetMask="255.255.255.0" xmi:id="ut-ca1-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.49" SubnetMask="255.255.255.0" xmi:id="ut-mi-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.45" SubnetMask="255.255.255.0" xmi:id="ut-co-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.54" SubnetMask="255.255.255.0" xmi:id="co-ut-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.56" SubnetMask="255.255.255.0" xmi:id="co-ne-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.57" SubnetMask="255.255.255.0" xmi:id="co-tx-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.65" SubnetMask="255.255.255.0" xmi:id="ne-co-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.68" SubnetMask="255.255.255.0" xmi:id="ne-il-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.86" SubnetMask="255.255.255.0" xmi:id="il-ne-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.82" SubnetMask="255.255.255.0" xmi:id="il-wa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.102" SubnetMask="255.255.255.0" xmi:id="il-pa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.94" SubnetMask="255.255.255.0" xmi:id="mi-ut-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.49" SubnetMask="255.255.255.0" xmi:id="mi-nj-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.141" SubnetMask="255.255.255.0" xmi:id="mi-ny-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.101" SubnetMask="255.255.255.0" xmi:id="pa-il-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.114" SubnetMask="255.255.255.0" xmi:id="pa-ga-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.144" SubnetMask="255.255.255.0" xmi:id="pa-ny-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.132" SubnetMask="255.255.255.0" xmi:id="pa-nj-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.142" SubnetMask="255.255.255.0" xmi:id="ny-mi-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.143" SubnetMask="255.255.255.0" xmi:id="ny-pa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.145" SubnetMask="255.255.255.0" xmi:id="ny-dc-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.136" SubnetMask="255.255.255.0" xmi:id="nj-mi-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.131" SubnetMask="255.255.255.0" xmi:id="nj-pa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.133" SubnetMask="255.255.255.0" xmi:id="nj-dc-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.121" SubnetMask="255.255.255.0" xmi:id="dc-tx-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.146" SubnetMask="255.255.255.0" xmi:id="dc-ny-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.134" SubnetMask="255.255.255.0" xmi:id="dc-nj-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.113" SubnetMask="255.255.255.0" xmi:id="ga-pa-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.111" SubnetMask="255.255.255.0" xmi:id="ga-tx-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.73" SubnetMask="255.255.255.0" xmi:id="tx-ca2-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.75" SubnetMask="255.255.255.0" xmi:id="tx-co-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.122" SubnetMask="255.255.255.0" xmi:id="tx-dc-ip"/>
  <TIM:CIM_StaticIPAssignmentSettingData IPv4Address="10.0.5.112" SubnetMask="255.255.255.0" xmi:id="tx-ga-ip"/>
    
  <!-- the interconnection networks (21) (MaxConnections = 2 => PPP) -->
  <TIM:TIM_LinkConnectivityCollection InstanceID="ca1-wa" MaxConnections="2" xmi:id="ca1-wa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ca2-wa" MaxConnections="2" xmi:id="ca2-wa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="il-wa" MaxConnections="2" xmi:id="il-wa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ca1-ca2" MaxConnections="2" xmi:id="ca1-ca2"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ca1-ut" MaxConnections="2" xmi:id="ca1-ut"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ca2-tx" MaxConnections="2" xmi:id="ca2-tx"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="mi-ut" MaxConnections="2" xmi:id="mi-ut"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="co-ut" MaxConnections="2" xmi:id="co-ut"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="co-ne" MaxConnections="2" xmi:id="co-ne"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="co-tx" MaxConnections="2" xmi:id="co-tx"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="il-ne" MaxConnections="2" xmi:id="il-ne"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="il-pa" MaxConnections="2" xmi:id="il-pa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="mi-nj" MaxConnections="2" xmi:id="mi-nj"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="mi-ny" MaxConnections="2" xmi:id="mi-ny"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ga-pa" MaxConnections="2" xmi:id="ga-pa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ny-pa" MaxConnections="2" xmi:id="ny-pa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="nj-pa" MaxConnections="2" xmi:id="nj-pa"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="dc-ny" MaxConnections="2" xmi:id="dc-ny"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="dc-nj" MaxConnections="2" xmi:id="dc-nj"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="dc-tx" MaxConnections="2" xmi:id="dc-tx"/>
  <TIM:TIM_LinkConnectivityCollection InstanceID="ga-tx" MaxConnections="2" xmi:id="ga-tx"/>
    
  <!-- node associations to the testbed (14) -->  
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#WA"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#CA1"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#CA2"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#UT"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#CO"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#NE"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#IL"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#MI"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#PA"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#NY"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#NJ"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#DC"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#GA"/>
  <TIM:CIM_SystemComponent GroupComponent="#nsfnet" PartComponent="#TX"/>  
  
  <!-- nets associations to the testbed (21) -->
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ca1-wa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ca2-wa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#il-wa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ca1-ca2"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ca1-ut"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ca2-tx"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#mi-ut"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#co-ut"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#co-ne"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#co-tx"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#il-ne"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#il-pa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#mi-nj"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#mi-ny"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ga-pa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ny-pa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#nj-pa"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#dc-ny"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#dc-nj"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#dc-tx"/>
  <TIM:CIM_HostedCollection Antecedent="#nsfnet" Dependent="#ga-tx"/>
  
  <!-- interfaces associations to networks (42) -->
  <TIM:TIM_MemberOfLink Collection="#ca1-wa" Member="#ca1-wa-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca1-wa" Member="#wa-ca1-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca2-wa" Member="#ca2-wa-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca2-wa" Member="#wa-ca2-if"/>
  <TIM:TIM_MemberOfLink Collection="#il-wa" Member="#il-wa-if"/>
  <TIM:TIM_MemberOfLink Collection="#il-wa" Member="#wa-il-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca1-ca2" Member="#ca1-ca2-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca1-ca2" Member="#ca2-ca1-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca1-ut" Member="#ca1-ut-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca1-ut" Member="#ut-ca1-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca2-tx" Member="#ca2-tx-if"/>
  <TIM:TIM_MemberOfLink Collection="#ca2-tx" Member="#tx-ca2-if"/>
  <TIM:TIM_MemberOfLink Collection="#mi-ut" Member="#mi-ut-if"/>
  <TIM:TIM_MemberOfLink Collection="#mi-ut" Member="#ut-mi-if"/>
  <TIM:TIM_MemberOfLink Collection="#co-ut" Member="#co-ut-if"/>
  <TIM:TIM_MemberOfLink Collection="#co-ut" Member="#ut-co-if"/>
  <TIM:TIM_MemberOfLink Collection="#co-ne" Member="#co-ne-if"/>
  <TIM:TIM_MemberOfLink Collection="#co-ne" Member="#ne-co-if"/>
  <TIM:TIM_MemberOfLink Collection="#co-tx" Member="#co-tx-if"/>
  <TIM:TIM_MemberOfLink Collection="#co-tx" Member="#tx-co-if"/>
  <TIM:TIM_MemberOfLink Collection="#il-ne" Member="#il-ne-if"/>
  <TIM:TIM_MemberOfLink Collection="#il-ne" Member="#ne-il-if"/>
  <TIM:TIM_MemberOfLink Collection="#il-pa" Member="#il-pa-if"/>
  <TIM:TIM_MemberOfLink Collection="#il-pa" Member="#pa-il-if"/>
  <TIM:TIM_MemberOfLink Collection="#mi-nj" Member="#mi-nj-if"/>
  <TIM:TIM_MemberOfLink Collection="#mi-nj" Member="#nj-mi-if"/>
  <TIM:TIM_MemberOfLink Collection="#mi-ny" Member="#mi-ny-if"/>
  <TIM:TIM_MemberOfLink Collection="#mi-ny" Member="#ny-mi-if"/>
  <TIM:TIM_MemberOfLink Collection="#ga-pa" Member="#ga-pa-if"/>
  <TIM:TIM_MemberOfLink Collection="#ga-pa" Member="#pa-ga-if"/>
  <TIM:TIM_MemberOfLink Collection="#ny-pa" Member="#ny-pa-if"/>
  <TIM:TIM_MemberOfLink Collection="#ny-pa" Member="#pa-ny-if"/>
  <TIM:TIM_MemberOfLink Collection="#nj-pa" Member="#nj-pa-if"/>
  <TIM:TIM_MemberOfLink Collection="#nj-pa" Member="#pa-nj-if"/>
  <TIM:TIM_MemberOfLink Collection="#dc-ny" Member="#dc-ny-if"/>
  <TIM:TIM_MemberOfLink Collection="#dc-ny" Member="#ny-dc-if"/>
  <TIM:TIM_MemberOfLink Collection="#dc-nj" Member="#dc-nj-if"/>
  <TIM:TIM_MemberOfLink Collection="#dc-nj" Member="#nj-dc-if"/>
  <TIM:TIM_MemberOfLink Collection="#dc-tx" Member="#dc-tx-if"/>
  <TIM:TIM_MemberOfLink Collection="#dc-tx" Member="#tx-dc-if"/>
  <TIM:TIM_MemberOfLink Collection="#ga-tx" Member="#ga-tx-if"/>
  <TIM:TIM_MemberOfLink Collection="#ga-tx" Member="#tx-ga-if"/>
  
  <!-- IPv4 associations to loopback interfaces (14) -->
  <TIM:CIM_ElementSettingData ManagedElement="#wa-lo" SettingData="#wa-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca1-lo" SettingData="#ca1-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca2-lo" SettingData="#ca2-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ut-lo" SettingData="#ut-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#co-lo" SettingData="#co-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ne-lo" SettingData="#ne-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#il-lo" SettingData="#il-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#mi-lo" SettingData="#mi-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#pa-lo" SettingData="#pa-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ny-lo" SettingData="#ny-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#nj-lo" SettingData="#nj-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#dc-lo" SettingData="#dc-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ga-lo" SettingData="#ga-lo-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#tx-lo" SettingData="#tx-lo-ip"/>
  
  <!-- IPv4 associations to PPP interfaces (42) -->
  <TIM:CIM_ElementSettingData ManagedElement="#ca1-wa-if" SettingData="#ca1-wa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#wa-ca1-if" SettingData="#wa-ca1-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca2-wa-if" SettingData="#ca2-wa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#wa-ca2-if" SettingData="#wa-ca2-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#il-wa-if" SettingData="#il-wa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#wa-il-if" SettingData="#wa-il-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca1-ca2-if" SettingData="#ca1-ca2-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca2-ca1-if" SettingData="#ca2-ca1-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca1-ut-if" SettingData="#ca1-ut-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ut-ca1-if" SettingData="#ut-ca1-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ca2-tx-if" SettingData="#ca2-tx-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#tx-ca2-if" SettingData="#tx-ca2-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#mi-ut-if" SettingData="#mi-ut-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ut-mi-if" SettingData="#ut-mi-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#co-ut-if" SettingData="#co-ut-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ut-co-if" SettingData="#ut-co-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#co-ne-if" SettingData="#co-ne-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ne-co-if" SettingData="#ne-co-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#co-tx-if" SettingData="#co-tx-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#tx-co-if" SettingData="#tx-co-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#il-ne-if" SettingData="#il-ne-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ne-il-if" SettingData="#ne-il-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#il-pa-if" SettingData="#il-pa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#pa-il-if" SettingData="#pa-il-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#mi-nj-if" SettingData="#mi-nj-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#nj-mi-if" SettingData="#nj-mi-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#mi-ny-if" SettingData="#mi-ny-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ny-mi-if" SettingData="#ny-mi-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ga-pa-if" SettingData="#ga-pa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#pa-ga-if" SettingData="#pa-ga-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ny-pa-if" SettingData="#ny-pa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#pa-ny-if" SettingData="#pa-ny-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#nj-pa-if" SettingData="#nj-pa-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#pa-nj-if" SettingData="#pa-nj-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#dc-ny-if" SettingData="#dc-ny-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ny-dc-if" SettingData="#ny-dc-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#dc-nj-if" SettingData="#dc-nj-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#nj-dc-if" SettingData="#nj-dc-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#dc-tx-if" SettingData="#dc-tx-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#tx-dc-if" SettingData="#tx-dc-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#ga-tx-if" SettingData="#ga-tx-ip"/>
  <TIM:CIM_ElementSettingData ManagedElement="#tx-ga-if" SettingData="#tx-ga-ip"/>
    
  <!-- loopback interfaces associations to nodes (14) -->
  <TIM:CIM_HostedAccessPoint Antecedent="#WA" Dependent="#wa-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA1" Dependent="#ca1-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA2" Dependent="#ca2-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#UT" Dependent="#ut-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CO" Dependent="#co-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NE" Dependent="#ne-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#IL" Dependent="#il-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#MI" Dependent="#mi-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#PA" Dependent="#pa-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NY" Dependent="#ny-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NJ" Dependent="#nj-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#DC" Dependent="#dc-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#GA" Dependent="#ga-lo"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#TX" Dependent="#tx-lo"/>  
  
  <!-- PPP interfaces associations to nodes (42) -->
  <TIM:CIM_HostedAccessPoint Antecedent="#CA1" Dependent="#ca1-wa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#WA" Dependent="#wa-ca1-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA2" Dependent="#ca2-wa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#WA" Dependent="#wa-ca2-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#IL" Dependent="#il-wa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#WA" Dependent="#wa-il-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA1" Dependent="#ca1-ca2-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA2" Dependent="#ca2-ca1-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA1" Dependent="#ca1-ut-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#UT" Dependent="#ut-ca1-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CA2" Dependent="#ca2-tx-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#TX" Dependent="#tx-ca2-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#MI" Dependent="#mi-ut-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#UT" Dependent="#ut-mi-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CO" Dependent="#co-ut-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#UT" Dependent="#ut-co-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CO" Dependent="#co-ne-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NE" Dependent="#ne-co-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#CO" Dependent="#co-tx-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#TX" Dependent="#tx-co-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#IL" Dependent="#il-ne-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NE" Dependent="#ne-il-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#IL" Dependent="#il-pa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#PA" Dependent="#pa-il-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#MI" Dependent="#mi-nj-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NJ" Dependent="#nj-mi-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#MI" Dependent="#mi-ny-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NY" Dependent="#ny-mi-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#GA" Dependent="#ga-pa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#PA" Dependent="#pa-ga-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NY" Dependent="#ny-pa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#PA" Dependent="#pa-ny-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NJ" Dependent="#nj-pa-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#PA" Dependent="#pa-nj-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#DC" Dependent="#dc-ny-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NY" Dependent="#ny-dc-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#DC" Dependent="#dc-nj-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#NJ" Dependent="#nj-dc-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#DC" Dependent="#dc-tx-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#TX" Dependent="#tx-dc-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#GA" Dependent="#ga-tx-if"/>
  <TIM:CIM_HostedAccessPoint Antecedent="#TX" Dependent="#tx-ga-if"/>
    
  <!-- the QoS constrainst for each link (21). This example uses delay, loss and duplication parameters -->
  <TIM:TIM_TransmissionCharacteristics InstanceID="ca1-wa-qos" xmi:id="ca1-wa-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>
  <TIM:TIM_TransmissionCharacteristics InstanceID="ca2-wa-qos" xmi:id="ca2-wa-qos" DelayMean="6" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="il-wa-qos" xmi:id="il-wa-qos" DelayMean="15" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="ca1-ca2-qos" xmi:id="ca1-ca2-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>
  <TIM:TIM_TransmissionCharacteristics InstanceID="ca1-ut-qos" xmi:id="ca1-ut-qos" DelayMean="6" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="ca2-tx-qos" xmi:id="ca2-tx-qos" DelayMean="7.5" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="mi-ut-qos" xmi:id="mi-ut-qos" DelayMean="15" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="co-ut-qos" xmi:id="co-ut-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="co-ne-qos" xmi:id="co-ne-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="co-tx-qos" xmi:id="co-tx-qos" DelayMean="3.75" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>            
  <TIM:TIM_TransmissionCharacteristics InstanceID="il-ne-qos" xmi:id="il-ne-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="il-pa-qos" xmi:id="il-pa-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="mi-nj-qos" xmi:id="mi-nj-qos" DelayMean="6" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="mi-ny-qos" xmi:id="mi-ny-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>
  <TIM:TIM_TransmissionCharacteristics InstanceID="ga-pa-qos" xmi:id="ga-pa-qos" DelayMean="5.25" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="ny-pa-qos" xmi:id="ny-pa-qos" DelayMean="3.75" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="nj-pa-qos" xmi:id="nj-pa-qos" DelayMean="6" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="dc-ny-qos" xmi:id="dc-ny-qos" DelayMean="6" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="dc-nj-qos" xmi:id="dc-nj-qos" DelayMean="3" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  <TIM:TIM_TransmissionCharacteristics InstanceID="dc-tx-qos" xmi:id="dc-tx-qos" DelayMean="15" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>            
  <TIM:TIM_TransmissionCharacteristics InstanceID="ga-tx-qos" xmi:id="ga-tx-qos" DelayMean="7.5" LossProbabilityValue="0.001" DuplicationProbabilityValue="0.0001"/>  
  
  <!-- QoS constrainst associations to links (21) -->
  <TIM:TIM_LinkTransmissionElement Antecedent="#ca1-wa" Dependent="#ca1-wa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ca2-wa" Dependent="#ca2-wa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#il-wa" Dependent="#il-wa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ca1-ca2" Dependent="#ca1-ca2-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ca1-ut" Dependent="#ca1-ut-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ca2-tx" Dependent="#ca2-tx-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#mi-ut" Dependent="#mi-ut-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#co-ut" Dependent="#co-ut-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#co-ne" Dependent="#co-ne-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#co-tx" Dependent="#co-tx-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#il-ne" Dependent="#il-ne-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#il-pa" Dependent="#il-pa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#mi-nj" Dependent="#mi-nj-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#mi-ny" Dependent="#mi-ny-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ga-pa" Dependent="#ga-pa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ny-pa" Dependent="#ny-pa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#nj-pa" Dependent="#nj-pa-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#dc-ny" Dependent="#dc-ny-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#dc-nj" Dependent="#dc-nj-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#dc-tx" Dependent="#dc-tx-qos"/>
  <TIM:TIM_LinkTransmissionElement Antecedent="#ga-tx" Dependent="#ga-tx-qos"/>

</xmi:XMI>
